name: Deploy Package

on:
  push:
    branches:
      - python-packaging

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        environment-file: env.yml
        activate-environment: myenv

    - name: List available artifacts
      run: |
        echo "Available artifacts:"
        gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: dist

    - name: Install the package
      run: pip install dist/*.whl

    - name: Run nonstandardcode.py
      run: python -m mypackage.nonstandardcode
