# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Conda Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        activate-environment: mle-dev
        environment-file: environment
        auto-activate-base: false

    - name: Install dependencies
      run: conda env update --file environment --name mle-dev

    - name: Run flake8
      run: |
        conda init
        conda activate mle-dev
        flake8 nonstandardcode.py

    - name: Run nonstandardcode.py
      run: |
        conda init
        conda activate mle-dev
        python nonstandardcode.py
